# Generated by Django 6.0.2 on 2026-03-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobapplication_application_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
